name: Code Coverage Summary Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xdebug

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      # Run PHPUnit to generate coverage
      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-cobertura=coverage.cobertura.xml

      # Generate code coverage summary
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml

      # Upload the coverage file as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.cobertura.xml
