on: push
name: Deploy to FTP
jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 188.165.230.7
        username: ${{ secrets.FTP_USERNAME }}  
        password: ${{ secrets.FTP_PASSWORD }} 
        local-dir: ./  
        server-dir: /www/  
        protocol: ftp  
        exclude: .github/
        dry-run: false  
